// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import DataProvider from "./context/DataProvider.js";
import { ClerkProvider } from '@clerk/nextjs'
import SyncUserToDB from "./components/SyncUserToDb";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`antialiased`}
          // ${geistSans.variable} ${geistMono.variable} 
        >
          <DataProvider>
            <Navbar />
            <SyncUserToDB/>
            {children}
            <Footer />
          </DataProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
